### PR TITLE
Fixed input for compatibility w/ older versions

### PR DESCRIPTION
**Pull request by Tiagochicoo**
hey!
Please check if this generates any issues with newer versions..

Fixed input for compatibility w/ older versions.

### CODE REVIEW

**Comment by edithturn** [comment]
Tiago, let me check them! 
Thank you so much! :)

**Review by edithturn — COMMENTED** [review]
Screenshot from 2021-03-23 21-36-08

@Tiagochicoo,
I tested It with Python 2.7.17, I didn't apply your changes and It looks like is working fine for python2 too.  
Please, let me see If I am not seeing something, and how this script could help.

**Comment by Tiagochicoo** [comment]
You can see the issue here on the 42 Lisboa's Macs that use python 2.7.16. It might be a good idea to have a note on the readme :)

**not using ""**
python

**using ""**
python2

**Comment by edithturn** [comment]
Thank you @Tiagochicoo , I will test in the 42 Machine and I will add the note, thank you for your time!

**Pull request closed without merging**
